// Plantillas oficiales Mundial 2026 (nombres en formato ESPN, iguales a los goleadores del sync).
// Ordenadas: delanteros → mediocampistas → defensas → arqueros. Solo las 4 selecciones semifinalistas.
export const ROSTERS: Record<string, string[]> = {
  "France": [
    "B. Barcola",
    "D. Doué",
    "J. Mateta",
    "K. Mbappé",
    "M. Thuram",
    "O. Dembélé",
    "A. Rabiot",
    "A. Tchouaméni",
    "M. Akliouche",
    "M. Koné",
    "M. Olise",
    "N. Kanté",
    "R. Cherki",
    "W. Zaïre-Emery",
    "D. Upamecano",
    "I. Konaté",
    "J. Koundé",
    "L. Digne",
    "L. Hernández",
    "M. Gusto",
    "M. Lacroix",
    "T. Hernández",
    "W. Saliba",
    "B. Samba",
    "M. Maignan",
    "R. Risser"
  ],
  "Spain": [
    "B. Iglesias",
    "F. Torres",
    "L. Yamal",
    "M. Oyarzabal",
    "N. Williams",
    "V. Muñoz",
    "Á. Baena",
    "D. Olmo",
    "F. Ruiz",
    "Gavi",
    "M. Llorente",
    "M. Merino",
    "M. Zubimendi",
    "Pedri",
    "Rodri",
    "Y. Pino",
    "A. Grimaldo",
    "A. Laporte",
    "E. García",
    "M. Cucurella",
    "M. Pubill",
    "P. Cubarsí",
    "P. Porro",
    "D. Raya",
    "J. García",
    "U. Simón"
  ],
  "England": [
    "A. Gordon",
    "B. Saka",
    "H. Kane",
    "I. Toney",
    "M. Rashford",
    "M. Rogers",
    "N. Madueke",
    "O. Watkins",
    "D. Rice",
    "E. Anderson",
    "E. Eze",
    "J. Bellingham",
    "J. Henderson",
    "K. Mainoo",
    "D. Burn",
    "D. Spence",
    "E. Konsa",
    "J. Quansah",
    "J. Stones",
    "M. Guéhi",
    "N. O'Reilly",
    "R. James",
    "T. Chalobah",
    "D. Henderson",
    "J. Pickford",
    "J. Trafford"
  ],
  "Argentina": [
    "G. Simeone",
    "J. Álvarez",
    "J. López",
    "L. Martínez",
    "L. Messi",
    "N. González",
    "A. Mac Allister",
    "E. Fernández",
    "E. Palacios",
    "G. Lo Celso",
    "L. Paredes",
    "N. Paz",
    "R. De Paul",
    "T. Almada",
    "V. Barco",
    "C. Romero",
    "F. Medina",
    "G. Montiel",
    "N. Molina",
    "N. Otamendi",
    "N. Tagliafico",
    "E. Martínez",
    "G. Rulli",
    "J. Musso"
  ]
}

export function rosterFor(team: string | null | undefined): string[] {
  return team ? (ROSTERS[team] ?? []) : []
}
